music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<gform_id>[0-9]+)/export_csv/$', views.export_csv, name="export_csv"),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^register/$', views.register, name='register'),
    url(r'^(?P<gform_id>[0-9]+)/user/(?P<user_id>[0-9]+)/$', views.filler, name='filler'),
    url(r'^(?P<gform_id>[0-9]+)/user/(?P<user_id>[0-9]+)/link$', views.link, name='link'),
    url(r'^(?P<gform_id>[0-9]+)/user/(?P<user_id>[0-9]+)/link$', views.responses, name='responses'),

    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<gform_id>[0-9]+)/$', views.detail, name='detail'),
#     url(r'^(?P<song_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
#     url(r'^songs/(?P<filter_by>[a-zA_Z]+)/$', views.songs, name='songs'),
    url(r'^create_form/$', views.create_form, name='create_form'),
    url(r'^(?P<gform_id>[0-9]+)/create_question/$', views.create_question, name='create_question'),
    url(r'^(?P<gform_id>[0-9]+)/delete_question/(?P<question_id>[0-9]+)/$', views.delete_question, name='delete_question'),
#     url(r'^(?P<album_id>[0-9]+)/favorite_album/$', views.favorite_album, name='favorite_album'),
    url(r'^(?P<gform_id>[0-9]+)/delete_form/$', views.delete_form, name='delete_form'),
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    #url(r'^', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
# # -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import Permission, User
from django.db import models


# class Album(models.Model):
#     user = models.ForeignKey(User, default=1)
#     artist = models.CharField(max_length=250)
#     album_title = models.CharField(max_length=500)
#     genre = models.CharField(max_length=100)
#     album_logo = models.FileField()
#     is_favorite = models.BooleanField(default=False)

#     def __str__(self):
#         return self.album_title + ' - ' + self.artist


# class Song(models.Model):
#     album = models.ForeignKey(Album, on_delete=models.CASCADE)
#     song_title = models.CharField(max_length=250)
#     audio_file = models.FileField(default='')
#     is_favorite = models.BooleanField(default=False)

#     def __str__(self):
#         return self.song_title

# # First - UserID, FormID, FormName, FormDescr
# # Second - QuesID, Label, Type, Text
TYPE_CHOICES = (
    ('multiline','Multi Line Text'),
    ('singleline', 'Single line Text'),
    ('number', 'Number'),
    ('num_range', 'Numeric Range'),
    ('url','URL'),
    ('checkbox','Checkbox'),
    ('dropdown','Dropdown'),
    ('radio','Radio Buttons'),
    ('file_upload', 'Upload File'),
    ('email', 'E-mail')
)


class Gform(models.Model):
    user = models.ForeignKey(User, default=1)
    # form_id = models.IntegerField(default=1)
    gform_name = models.CharField(max_length=50,default="")
    gform_desc = models.CharField(max_length=500,default="")
    	

    def __str__(self):
        return self.gform_name + " " + self.gform_desc


class Question(models.Model):
    #ques_id = models.IntegerField(default=1)
    gform = models.ForeignKey(Gform, on_delete=models.CASCADE, default=1)
    #ques_type = models.CharField(max_length=500)
    ques_type = models.CharField(max_length=50, choices=TYPE_CHOICES, default="multiline")
    ques_text = models.CharField(max_length=500)
    choices = models.CharField(max_length=500,default="")
    is_req = models.BooleanField(default=False)
    is_vis = models.BooleanField(default=False)
    #color = models.CharField(max_length=6, choices=COLOR_CHOICES, default='green')


    def __str__(self):
        return self.ques_text + " " +self.ques_type

    def choices_as_list(self):
    	return self.choices.split(',')


class Response(models.Model):

	gform = models.ForeignKey(Gform, on_delete=models.CASCADE, default=1)
	resp_text = models.CharField(max_length=2000)

	def __str__(self):
		return self.resp_text


# # class Data1(models.Model):
# #     client= models.CharField(max_length=100,default='Hi')
# #     Answer1= models.CharField(max_length=100,default='Hi')
# #     Answer2= models.CharField(max_length=200,default='Hi')
# #     Answer3= models.CharField(max_length=200,default='Hi')
    
# # class Data2(models.Model):
# #     client= models.CharField(max_length=100,default='Hi')
# #     Answer1= models.CharField(max_length=100,default='Hi')
# #     Answer2= models.CharField(max_length=200,default='Hi')
# #     Answer3= models.CharField(max_length=200,default='Hi')

# # class QuesType(models.Model):
# #     TypeID= models.IntegerField()
# #     Type= models.CharField(max_length=50,default='Hi')

# # class UserForm(models.Model):
# #     UserID= models.IntegerField()
# #     FormID= models.IntegerField()
# #     FormName=models.CharField(max_length=100,default='Hi')

# #     class Meta:
        
# #         unique_together=(("UserID","FormID"),)

# # class Question(models.Model):
# #     QuesID= models.IntegerField()
# #     FormID= models.ForeignKey(UserForm,on_delete=models.CASCADE)
# #     TypeID= models.IntegerField()
# #     Questxt= models.CharField(max_length=100,default='Hi')

# #     class Meta:
# #         unique_together=(("QuesID","FormID"),)


# # class Mcq(models.Model):
# #     QuesID= models.ForeignKey(Question,on_delete=models.CASCADE)
# #     Options= models.CharField(max_length=100,default='Hi')

music/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Gform, Question


# class AlbumForm(forms.ModelForm):

#     class Meta:
#         model = Album
#         fields = ['artist', 'album_title', 'genre', 'album_logo']


class GformForm(forms.ModelForm):

    class Meta:
        model = Gform
        fields = ['gform_name', 'gform_desc']


# class SongForm(forms.ModelForm):

#     class Meta:
#         model = Song
#         fields = ['song_title', 'audio_file']

class QuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ['ques_type', 'ques_text','choices', 'is_req', 'is_vis']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class EditProfileForm(UserChangeForm):
    password=None

    class Meta:
        model=User
        fields = ('username',)

music/views.py
# # -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from .forms import UserForm, EditProfileForm, GformForm, QuestionForm
#from .models import Album, Song
from .models import Gform, Question, Response
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from django.urls import reverse
import csv


# AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
# IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']


# def create_album(request):
#     if not request.user.is_authenticated():
#         return render(request, 'music/login.html')
#     else:
#         form = AlbumForm(request.POST or None, request.FILES or None)
#         if form.is_valid():
#             album = form.save(commit=False)
#             album.user = request.user
#             album.album_logo = request.FILES['album_logo']
#             file_type = album.album_logo.url.split('.')[-1]
#             file_type = file_type.lower()
#             if file_type not in IMAGE_FILE_TYPES:
#                 context = {
#                     'album': album,
#                     'form': form,
#                     'error_message': 'Image file must be PNG, JPG, or JPEG',
#                 }
#                 return render(request, 'music/create_album.html', context)
#             album.save()
#             return render(request, 'music/detail.html', {'album': album})
#         context = {
#             "form": form,
#         }
#         return render(request, 'music/create_album.html', context)


def create_form(request):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        form = GformForm(request.POST or None)
        if form.is_valid():
            gform = form.save(commit=False)
            gform.user = request.user
            # album.album_logo = request.FILES['album_logo']
            # file_type = album.album_logo.url.split('.')[-1]
            # file_type = file_type.lower()
            # if file_type not in IMAGE_FILE_TYPES:
            #     context = {
            #         'album': album,
            #         'form': form,
            #         'error_message': 'Image file must be PNG, JPG, or JPEG',
            #     }
            #     return render(request, 'music/create_album.html', context)
            gform.save()
            return render(request, 'music/detail.html', {'gform': gform})
        context = {
            "form": form,
        }
        return render(request, 'music/create_form.html', context)



# def create_song(request, album_id):
#     form = SongForm(request.POST or None, request.FILES or None)
#     album = get_object_or_404(Album, pk=album_id)
#     if form.is_valid():
#         albums_songs = album.song_set.all()
#         for s in albums_songs:
#             if s.song_title == form.cleaned_data.get("song_title"):
#                 context = {
#                     'album': album,
#                     'form': form,
#                     'error_message': 'You already added that song',
#                 }
#                 return render(request, 'music/create_song.html', context)
#         song = form.save(commit=False)
#         song.album = album
#         song.audio_file = request.FILES['audio_file']
#         file_type = song.audio_file.url.split('.')[-1]
#         file_type = file_type.lower()
#         if file_type not in AUDIO_FILE_TYPES:
#             context = {
#                 'album': album,
#                 'form': form,
#                 'error_message': 'Audio file must be WAV, MP3, or OGG',
#             }
#             return render(request, 'music/create_song.html', context)

#         song.save()
#         return render(request, 'music/detail.html', {'album': album})
#     context = {
#         'album': album,
#         'form': form,
#     }
#     return render(request, 'music/create_song.html', context)


def create_question(request, gform_id):
    form = QuestionForm(request.POST or None)
    gform = get_object_or_404(Gform, pk=gform_id)
    if form.is_valid():
        form_questions = gform.question_set.all()
        for s in form_questions:
            if s.ques_text == form.cleaned_data.get("ques_text"):
                context = {
                    'gform': gform,
                    'form': form,
                    'error_message': 'You already added that question',
                }
                return render(request, 'music/create_question.html', context)
        question = form.save(commit=False)
        question.gform = gform
        #song.audio_file = request.FILES['audio_file']
        #file_type = song.audio_file.url.split('.')[-1]
        #file_type = file_type.lower()
        # if file_type not in AUDIO_FILE_TYPES:
        #     context = {
        #         'album': album,
        #         'form': form,
        #         'error_message': 'Audio file must be WAV, MP3, or OGG',
        #     }
        #     return render(request, 'music/create_song.html', context)
        #question.choices = choices
       	question.save()
        return render(request, 'music/detail.html', {'gform': gform})
    context = {
        'gform': gform,
        'form': form,
    }
    return render(request, 'music/create_question.html', context)


def filler(request, gform_id, user_id):
	user = request.user
	gform = get_object_or_404(Gform, pk=gform_id)
	return render(request, 'music/filler.html', {'gform':gform, 'user':user})

def link(request, gform_id, user_id):
	user=request.user
	gform = get_object_or_404(Gform, pk=gform_id)
	return render(request, 'music/link.html', {'gform':gform, 'user':user})

def results(request, gform_id, user_id):
	gform = get_object_or_404(Gform, pk=gform_id)
	context = {'gform':gform}
	return render(request, 'music/results.html', context)


def responses(request, gform_id, user_id):
	gform = get_object_or_404(Gform, pk=gform_id)

	if request.method == 'POST':
		
		# final = ""
		# for question in gform.question_set.all:
		# 	post.resp_text = request.POST.get(question.ques_text)
		# post.gform_id = gform_id
		# post.resp_text = final
		for question in gform.question_set.all():
		 	final = request.POST("ayush")
		post = Response(gform=gform_id, resp_text=final)
		post.save()

	return render(request, 'music/results.html', {'gform':gform})
		


# def delete_album(request, album_id):
#     album = Album.objects.get(pk=album_id)
#     album.delete()
#     albums = Album.objects.filter(user=request.user)
#     return render(request, 'music/index.html', {'albums': albums})


def delete_form(request, gform_id):
    gform = Gform.objects.get(pk=gform_id)
    gform.delete()
    gforms = Gform.objects.filter(user=request.user)
    return render(request, 'music/index.html', {'gforms': gforms})


# def delete_song(request, album_id, song_id):
#     album = get_object_or_404(Album, pk=album_id)
#     song = Song.objects.get(pk=song_id)
#     song.delete()
#     return render(request, 'music/detail.html', {'album': album})


def delete_question(request, gform_id, question_id):
    gform = get_object_or_404(Gform, pk=gform_id)
    question = Question.objects.get(pk=question_id)
    question.delete()
    return render(request, 'music/detail.html', {'gform': gform})


def detail(request, gform_id):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        user = request.user
        gform = get_object_or_404(Gform, pk=gform_id)
        return render(request, 'music/detail.html', {'gform': gform, 'user': user})


# def favorite(request, song_id):
#     song = get_object_or_404(Song, pk=song_id)
#     try:
#         if song.is_favorite:
#             song.is_favorite = False
#         else:
#             song.is_favorite = True
#         song.save()
#     except (KeyError, Song.DoesNotExist):
#         return JsonResponse({'success': False})
#     else:
#         return JsonResponse({'success': True})


# def favorite_album(request, album_id):
#     album = get_object_or_404(Album, pk=album_id)
#     try:
#         if album.is_favorite:
#             album.is_favorite = False
#         else:
#             album.is_favorite = True
#         album.save()
#     except (KeyError, Album.DoesNotExist):
#         return JsonResponse({'success': False})
#     else:
#         return JsonResponse({'success': True})


# def index(request):
#     if not request.user.is_authenticated():
#         return render(request, 'music/login.html')
#     else:
#         albums = Album.objects.filter(user=request.user)
#         song_results = Song.objects.all()
#         query = request.GET.get("q")
#         if query:
#             albums = albums.filter(
#                 Q(album_title__icontains=query) |
#                 Q(artist__icontains=query)
#             ).distinct()
#             song_results = song_results.filter(
#                 Q(song_title__icontains=query)
#             ).distinct()
#             return render(request, 'music/index.html', {
#                 'albums': albums,
#                 'songs': song_results,
#             })
#         else:
#             return render(request, 'music/index.html', {'albums': albums})


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
        #return 
    else:
        gforms = Gform.objects.filter(user=request.user)
        questions = Question.objects.all()
        query = request.GET.get("q")
        if query:
            gforms = gforms.filter(
                Q(gforms_title__icontains=query) |
                Q(gforms_desc__icontains=query)
            ).distinct()
            

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Forms{% endblock %}</title>
    {% load staticfiles %}
    <!-- <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

   <!--  <script src="{% static 'music/js/main.js' %}"></script> -->
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- !-- Header  -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Forms</a>
        </div>

        <!-- !-- Items  -->
        <div class="collapse navbar-collapse" id="topNavBar">
             <ul class="nav navbar-nav">
                <li class="{% block forms_active %}{% endblock %}"><a href="{% url 'music:index' %}">&nbsp; My Forms</a></li>
                {% comment %}<li class="{% block questions_active %}{% endblock %}"><a href="{% url 'music:questions' 'all' %}">&nbsp; Questions</a></li>{% endcomment %}
                <li class="{% block edit_profile_active %}{% endblock %}"><a href="{% url 'music:edit_profile' %}">&nbsp; Edit Profile</a></li>
                <li class="{% block change_password_active %}{% endblock %}"><a href="{% url 'music:change_password'  %}">&nbsp; Change Password</a></li> 
            </ul> 
           
            <!--<form class="navbar-form navbar-left" role="search" method="get" action="{% url 'music:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form> -->

            <ul class="nav navbar-nav navbar-right">
                 <li>
                    <a href="{% url 'music:create_form' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Form
                    </a>
                </li>
                <li>
                    <a href="{% url 'music:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li> 
            </ul>
          
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Forms{% endblock %}</title>
    {% load staticfiles %}
<!--     <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <!-- <script src="{% static 'music/js/main.js' %}"></script> -->
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

       <!--  Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
          <a class="navbar-brand" href="{% url 'music:index' %}">Forms</a> 
        </div>

       <!--  !-- Items  -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                {% comment %}
               <!--  <li class="{% block register_active %}{% endblock %}"><a href="{% url 'music:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'music:login_user' %}">Log In</a></li> -->
                {% endcomment %}
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}{{ gform }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

    
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' gform.id %}">
                       <!--  {% if album.album_logo %}
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %} -->
                    </a>
                    <ul class="nav nav-pills">
                        <li role="presentation">  <h1> <b> {{ gform.gform_name }} </b></h1> </li>
                        <li role="presentation"> <h2> {{ gform.gform_desc }} </h2> </li>
                    </ul>
                         <h5> Generated Form Link: </h5> 
                        <font color="red"> &nbsp; (current ip_address) + <br>{{ request.get_full_path }}user/{{ user.id }}/link </font>
                   
                   <!--  <h2>{{ album.artist }}</h2> -->
                </div>
            </div>
        </div>

       
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'music:detail' gform.id %}">View All</a></li>
                <li role="presentation"><a href="{% url 'music:create_question' gform.id %}">Add New Question</a></li> 
                <li role="presentation"><a href="{% url 'music:filler' gform.id user.id  %}">Preview</a></li> 
               


            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Questions</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}


                    <div class="table-responsive">
                        <div style="overflow-x:auto;">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Question type</th>
                            <th>Question text</th>
                            <th> Choices </th>
                            <th>Compulsary</th>
                            <th>Visible</th>
                            <th>Action</th>
                            
                        </tr>
                        </thead>
                        <tbody>
                        {% for question in gform.question_set.all %}
                            <tr>
                                <td>{{ question.ques_type }}</td>
                                <td>
                                    {{ question.ques_text }} 
                                </td>
                                <td>
                                   

                                   {{ question.choices }}
                                </td>
                                <td> 
                                {% if question.is_req %} True 
                                {% else %} False
                                {% endif %}</td>
                                <td>
                                    {% if question.is_vis %} True 
                                {% else %} False
                                {% endif %}
                                </td>

                                <td> <form action="{% url 'music:delete_question' gform.id question.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="question_id" value="{{ question.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                   </td>

                                  
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div></div>

                </div>
            </div> 

        </div>

    </div>

</div>

{% endblock %}

music/templates/music/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
 {% block title %}Google Forms{% endblock %} 
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- !-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Forms</h3>
        </div>
        {% if gforms %}
            {% for gform in gforms %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <div >
                            <h2>{{ gform.gform_name }}</h2>
                            <h4>{{ gform.gform_desc }}</h4>

                            <!--  View Details -->
                            <a href="{% url 'music:detail' gform.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album  -->
                            <form action="{% url 'music:delete_form' gform.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="gform_id" value="{{ gform.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>

                                <a href="{% url 'music:export_csv' gform.id %}" class="btn  btn-sm" role="button">Export CSV</a>
                                 <a href="#" class="btn  btn-sm" role="button">Add collaborator</a>
                            </form>

                         

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'music:create_form' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Form
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

   <!--  !-- If user searches and there are questions  -->
    {% if questions %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Questions</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>a</th>
                                    <th>b</th>
                                    <th>c</th>
                                    <th>d/th>
                                    <th>e</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for question in questions %}
                                    <tr>
                                        <td>{{ question.ques_text }}</td>
                                        <td>{{ question.ques_type }}</td>
                                        <td>
                                            abcd
                                        </td>
                                        <td>
                                            
                                            <a href="{% url 'music:detail' question.gform.id %}">{{ question.gform.gform_name }}</a>
                                        </td>
                                        <td>
                                            abcd
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

music/templates/music/results.html
{% extends 'music/base.html' %}
{% block title %}{{ gform }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}

<h1> {{ gform.gform_name }} </h1>
<h1> {{ gform.gform_desc }} </h1>

<ul>
{% for response in gform.response_set.all %}
	<li> {{ response.resp_text }} </li>
{% endfor %}

</ul>

{% endblock %}